export const details = [
	{
		img: "assets/images/imageMask-1.svg",
		title: "Acceleration",
		subject: "Physics",
		grade: 7,
		add: 2,
		subjectMeta: {
			units: 4,
			lessons: 18,
			topics: 4,
		},
		class: "Mr. Frank's Class B",
		noClass: false,
		classMeta: {
			students: 50,
			fromDate: "21-Jan-2020",
			toDate: "21-Aug-2020",
		},
		options: {
			preview: true,
			manageCourse: true,
			gradeSubmission: true,
			reports: true,
		},
		expired: false,
		favourite: true,
	},
	{
		img: "assets/images/imageMask-2.svg",
		title: "Displacement, Velocity and Speed",
		subject: "Physics 2",
		grade: 6,
		add: 3,
		subjectMeta: {
			units: 2,
			lessons: 15,
			topics: 20,
		},
		class: "No Classes",
		noClass: true,
		classMeta: {
			students: 0,
			fromDate: "",
			toDate: "",
		},
		options: {
			preview: true,
			manageCourse: false,
			gradeSubmission: false,
			reports: true,
		},
		expired: false,
		favourite: true,
	},
	{
		img: "assets/images/imageMask.svg",
		title: "Introduction to Biology: Microorganisms and how they affec...",
		subject: "Biology",
		grade: 4,
		add: 1,
		subjectMeta: {
			units: 5,
			lessons: 16,
			topics: 22,
		},
		class: "All Classes",
		noClass: false,
		classMeta: {
			students: 300,
			fromDate: "",
			toDate: "",
		},
		options: {
			preview: true,
			manageCourse: false,
			gradeSubmission: false,
			reports: true,
		},
		expired: false,
		favourite: true,
	},
	{
		img: "assets/images/imageMask-3.svg",
		title: "Introduction to High School Mathematics",
		subject: "Mathematics",
		grade: 8,
		add: 3,
		subjectMeta: {
			units: 0,
			lessons: 0,
			topics: 0,
		},
		class: "Mr. Frank's Class A",
		noClass: false,
		classMeta: {
			students: 44,
			fromDate: "14-Oct-2019",
			toDate: "20-Oct-2020",
		},
		options: {
			preview: true,
			manageCourse: true,
			gradeSubmission: true,
			reports: true,
		},
		expired: false,
		favourite: false,
	},
];
